### ISSUE TITLE
这没法用啊

### ISSUE THREAD

**Issue by ZYHUO** [zmh-program/web-chatgpt-qq-bot#1]
打开就是一片黑，根本看不到什么

**Comment by zmh-program** [comment]
请确保SocketIO的连接。
请使用Release中的install.sh进行一键安装，谢谢。
如果仍未奏效，请尝试1.1版本。

**Comment by ZYHUO** [comment]
那换1.1试试

**Comment by ZYHUO** [comment]
切换到1.1任不奏效

**Comment by ZYHUO** [comment]
生成的配置在/root/bot/web-chatgpt/web-chatgpt/config/config.cfg
但是config并没有生成任何东西
难道是这个错误吗

**Comment by zmh-program** [comment]
那得问Cloxl了 我主要负责前端
感觉现在有点混乱了[哭笑]
因为已经cd进去了 所以实际上配置文件应该在
/root/bot/web-chatgpt/config/config.cfg

打算在1.3中修复，最近没空，我还在上学[捂脸]

如果有问题可以加下QQ ProgramZmh

**Comment by ZYHUO** [comment]
那真是麻烦你了，我只会看得懂一点点代码，写都不会。更别说web了[捂脸]
我去问一下他

**Comment by zmh-program** [comment]
/root/bot/web-chatgpt/config/config.cfg
这个目录仍不奏效？😅
或者可以加一下我QQ详细说下[捂脸]😀

**Comment by ZYHUO** [comment]
ssh还没开，内存占用有点高，等会看看
你的QQ号是啥
