### ISSUE TITLE
很好昂，又是我

### ISSUE THREAD

**Issue by ZYHUO** [zmh-program/web-chatgpt-qq-bot#2]
还是老毛病，但是是python的，那个app.py有问题
SyntaxError: Non-ASCII character '\xe6' in file app.py on line 20, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
好像是编码问题
我的是欧洲的vps
正常install.sh没法用
flask没启动
命令为python app.py

**Comment by zmh-program** [comment]
第20行：       "\n无法连接 Docker！请排查以下错误: "
这或许是你的python外编码问题，请提供更多系统python信息。

**Comment by ZYHUO** [comment]
python app.py出来后只有这个

**Comment by ZYHUO** [comment]
python app.py出来后只有这个

**Comment by zmh-program** [comment]
例如，请提供你的python版本信息（推荐>=3.7），谢谢。

**Comment by ZYHUO** [comment]
Python 2.7.5
好像确实old了一点
先升级一下

**Comment by ZYHUO** [comment]
好可以了
谢谢
