### ISSUE TITLE
奇怪，配置下文件没有config

### ISSUE THREAD

**Issue by QianYu13** [zmh-program/web-chatgpt-qq-bot#3]
奇了个怪了，端口是开了的，但是没有监听端口 5000 的程序，也没生成配置文件config.cfg，是我配置的有问题嘛
![image](https://github.com/zmh-program/web-chatgpt-qq-bot/assets/74176788/69246fed-3f4e-4011-93db-709eef58cd00)
![image](https://github.com/zmh-program/web-chatgpt-qq-bot/assets/74176788/8633b7eb-8e99-4f5f-b444-096a993ec0ce)
![image](https://github.com/zmh-program/web-chatgpt-qq-bot/assets/74176788/2a17ce96-04a3-4f4c-9a12-a81fd55c7053)

**Comment by zmh-program** [comment]
应该是，请使用最新版本的install.sh安装并在项目目录输入`python3 app.py`检查。

**Comment by QianYu13** [comment]
已解决，用 Gunicorn 来运行 Flask 应用程序的监听，再用 nohup 命令来在后台运行 Gunicorn，之前是因为监听了然后退出了，导致一系列问题，我以为是后台监听
